#!/usr/bin/csh
set test_name = "$1"
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim0.log

vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc01.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim01.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc02.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim02.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc03.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim03.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc04.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim04.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc05.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim05.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc06.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim06.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc07.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim07.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc08.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim08.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc09.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim09.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc10.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim10.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc11.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim11.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc12.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim12.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc13.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim13.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc14.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim14.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc15.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim15.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc16.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim16.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc17.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim17.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc18.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim18.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc19.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim19.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc20.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim20.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc21.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim21.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc22.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim22.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc23.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim23.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc24.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim24.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc25.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim25.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc26.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim26.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc27.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim27.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc28.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim28.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc29.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim29.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc30.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim30.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc31.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim31.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc32.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim32.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc33.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim33.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc34.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim34.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc35.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim35.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc36.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim36.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc37.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim37.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc38.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim38.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc39.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim39.log
vcs -sverilog -ntb_opts uvm-1.1 -timescale=1ns/1ns +ntb_random_seed=value  +incdir+verif/sequences +incdir+verif/test +incdir+verif/top +incdir+verif/uart_tx_uvc u0tc40.sv ./verif/top/u0_top.sv -l uart_compile.log
./simv +UVM_TIMEOUT=5000000 -l ./logs/uart_sim40.log
# vcs -ntb_opts uvm-1.1 -ntb_opts -timescale=1ns/1ps +ntb_random_seed=0 -sverilog -debug_all +UVM_TESTNAME="$test_name" -R -l simv.log +incdir+student_src +incdir+student_src/cpu2ocp +incdir+student_src/cpu +incdir+student_src/ocp_slave +incdir+student_src/interface -f dut.vfiles student_src/cpu/cpu_pkg.sv student_src/ocp_slave/ocp_pkg.sv student_src/cpu2ocp/cpu2ocp_pkg.sv student_src/cpu2ocp/cpu2ocp_top_tb.sv
